### ISSUE TITLE
failed to connect to V-REP. Retrying...

### ISSUE THREAD

**Issue by haoshuiwuxiang** [harry-uglow/Deep-RL-Sim2Real#2]
Hello, I set up the environment according to the instructions and used VREP 3.6.1. 
At first, I failed to connect to vrep, and then I found that because my computer cpu only has 6 cores, I changed the parameter --num-processes to 6.
At this time, the error of connection vrep failure is not reported, but it runs for a period of time, and the specific code is executed:
obs, _, dones, infos = envs.step(action)
An error is reported, and debugging shows that the angle value is not obtained from vrep, which triggers the program assertion:
![image](https://user-images.githubusercontent.com/40374436/98082368-999b4080-1eb3-11eb-80ef-d756722e5f98.png)

![image](https://user-images.githubusercontent.com/40374436/98082529-d8c99180-1eb3-11eb-8cd5-7397906f49a0.png)

**Comment by harry-uglow** [comment]
Hi there,

I think I saw this issue on rare occasions myself but I don't think I discovered why. If I did I'm afraid I can't remember and unfortunately I'm not in a position to set all this up and test myself at the moment. I'm not sure why the get_joint_angles function is failing but you might be able to debug on V-REP or ask in the V-REP forum https://forum.coppeliarobotics.com/ 

Alternatively you could edit the code to handle this error. If it happens very rarely perhaps it's worth ignoring and moving on?

**Comment by harry-uglow** [comment]
Closing due to age.
