### ISSUE TITLE
Python API function report error 

### ISSUE THREAD

**Issue by CodingNovice7** [harry-uglow/Deep-RL-Sim2Real#6]
Thank you very much for your open source code to let me know curl. It seems to be a powerful method, but I encountered some problems when running your code. I hope you can provide some help. I use the virtual machine system Ubuntu 18.04, and the software is Coppelia simedu 4.1.0 and python 3.6.9. As required, I installed the corresponding environment and changed vrep.py and vrepconst.py to sim.py and simconst.py, remotoapi. However, when running sim.simxloadscene, the error shown in the figure still occurs. There was an error in sim.simxcallscriptfunction before, with the same error code 8, but I called a function to get the handle and made the changes as shown in the figure. Later, the function did not report an error. The official explanation of this error code 8 seems to be that this function causes an error on the server side. I don't know if there is a communication problem between Python and coppeliasim, but I run simpletest normally.This is all the bags I packed[https://ibb.co/Pz62LGM](url)[
https://ibb.co/rdDWxpx](url)[https://ibb.co/m5930Xw](url).
this is code adjusted
`import atexit
import os
import signal
import time
from subprocess import Popen, DEVNULL

import numpy as np
from gym import Env
# noinspection PyUnresolvedReferences
import platform
import sim

def check_for_errors(code):
    if code == sim.simx_return_ok:
        return
    elif code == sim.simx_return_timeout_flag:
        raise RuntimeError('The function timed out (probably the network is down or too slow)')
    elif code == sim.simx_return_novalue_flag:
        # Often, not really an error, so just ignore
        pass
    elif code == sim.simx_return_illegal_opmode_flag:
        raise RuntimeError('The specified operation mode is not supported for the given function')
    elif code == sim.simx_return_remote_error_flag:
        raise RuntimeError('The function caused an error on the server side (e.g. an invalid handle was specified)')
    elif code == sim.simx_return_split_progress_flag:
        raise RuntimeError('The communication thread is still processing previous split command of the same type')
    elif code == sim.simx_return_local_error_flag:
        raise RuntimeError('The function caused an error on the client side')
    elif code == sim.simx_return_initialize_error_flag:
        raise RuntimeError('A connection to vrep has not been made yet. Have you called connect()?')

# Function to check for errors when calling a remote API function
def catch_errors(input):
    print('input',input)
    if isinstance(input, tuple):
        code = input[0]
        values = input[1] if len(input) == 2 else input[1:]
    else:
        code = input
        values = None
        print('code', code)
    check_for_errors(code)

    return values

# Define the port number where communication will be made to the V-Rep server
base_port_num = 19997
# Define the host where this communication is taking place
host = '127.0.0.1'

scene_dir_path = os.path.join(os.getcwd(), 'Home/curl/PycharmProjects/pythonProject4/CURL/scenes/dish_rack_nr.ttt')
# Insert path here - perhaps abstract this away to a config file?
vrep_path = os.path.expanduser('~/Desktop/coppeliasim/coppeliaSim.sh')
# This allowed V-Rep to be run over SSH to an Ubuntu machine.
# See forum.coppeliarobotics.com/viewtopic.php?p=29772
xvfb_args = ['xvfb-run', '--auto-servernum', '--server-num=1']
     # if not platform.system() == 'Darwin' else []

class VrepEnv(Env):
    """
    An environment with behind-the-scenes handled by a scene in V-Rep. This abstract parent class
    allows its children to function as any regular OpenAI Gym environment, handling the
    set-up and tear-down of an associated V-Rep scene.
    """

    def __init__(self, scene_name, rank, headless):
        # Launch a V-Rep server
        # Read more here: http://www.coppeliarobotics.com/helpFiles/en/commandLine.htm
        port_num = base_port_num + rank
        remote_api_string = '-gREMOTEAPISERVERSERVICE_' + str(port_num) + '_FALSE_TRUE'
        args = [*xvfb_args, vrep_path, '-h' if headless else '', remote_api_string]
        self.cid = -1
        while self.cid == -1:
            self.process = Popen(args, preexec_fn=os.setsid, stdout=DEVNULL)
            time.sleep(6)
            self.cid = sim.simxStart(host, port_num, True, True, 5000, 5)
            if self.cid == -1:
                print(f"{rank} failed to connect to V-REP. Retrying...")
                try:
                    pgrp = os.getpgid(self.process.pid)
                    os.killpg(pgrp, signal.SIGKILL)
                except ProcessLookupError:
                    pass
        catch_errors(sim.simxSynchronous(self.cid, enable=True))
        scene_path = os.path.join(scene_dir_path, 'dish_rack_nr.ttt')
        #f'{scene_name}.ttt'
        catch_errors(sim.simxLoadScene(self.cid, scene_path,0, sim.simx_opmode_blocking))
        atexit.register(self.close)

    # Function to call a Lua function in V-Rep
    # Read more here: http://www.coppeliarobotics.com/helpFiles/en/remoteApiExtension.htm
    def call_lua_function(self, lua_function, ints=[], floats=[], strings=[],
                          bytes=bytearray(), opmode=sim.simx_opmode_blocking):
        errorcode,scripthandle=sim.simxGetObjectHandle(self.cid,'remote_api', opmode=sim.simx_opmode_block)
        return_code, out_ints, out_floats, out_strings, out_buffer = sim.simxCallScriptFunction(
            self.cid, 'remote_api', scripthandle, lua_function, ints,
            floats, strings, bytes, opmode)
        check_for_errors(return_code)

        return out_ints, out_floats, out_strings, out_buffer

    def close(self):
        # Shutdown
        print("Closing VREP")
        sim.simxStopSimulation(self.cid, sim.simx_opmode_blocking)
        sim.simxFinish(self.cid)
        atexit.unregister(self.close)
        try:
            pgrp = os.getpgid(self.process.pid)
            os.killpg(pgrp, signal.SIGKILL)
        except ProcessLookupError:
            pass

    # Rendering not implemented by default. See DishRackEnv for a more specific implementation.
    def render(self, mode='human'):
        pass

    # Returns a vector from one item to another under "from"s axes (not the world axes).
    def get_vector(self, from_handle, to_handle):
        pose = catch_errors(sim.simxGetObjectPosition(
            self.cid, to_handle, from_handle, sim.simx_opmode_blocking))
        return np.array(pose)

    def get_position(self, handle):
        return self.get_vector(-1, handle)

    def get_distance(self, from_handle, to_handle):
        return np.linalg.norm(self.get_vector(from_handle, to_handle))
`
this is error information
[https://ibb.co/TtLKMPm](url)
[https://ibb.co/GkysFQZ](url)
[https://ibb.co/LR57z50](url)

**Comment by harry-uglow** [comment]
Thanks for your interest in the project. Sorry but I don't have any more information to add to this off the top of my head and am not available to investigate issues on this any more. Best of luck.
