### ISSUE TITLE
A doubt more than an issue

### ISSUE THREAD

**Issue by rohitdhak** [harry-uglow/Deep-RL-Sim2Real#7]
I would like to know, how can i replicate the experiment of reaching a point in space over a wall. 

I tried python python enjoy.py --load-dir trained_models/ppo --env-name "reach_over_wall_cartesian_control" --pipeline wall, but the connection is not successful. However I think i will resolve that. 

I also wanted to know about the hierarchy of the environments , since there are so many of them 
VrepEnv
SawyerEnv
SawyerReacherEnv
GoalDrivenEnv

So If I want to train a manipulator for reaching task, how should iI be navigating through your repo
I am only interested in reaching task (first without wall, but all over the workspace and then with obstacle)

I would like to have a bit of guidance from you for me to achieve this task. 

Also if i am not wrong you are using a pre-defined curriculum (defined in the pipelines.py), right? 
Have you ever worked with automatic generation of the curriculum? 

I would be grateful for the help.

**Comment by harry-uglow** [comment]
Hi Rohi,

Thanks for your interest in CuRL. I can't help with the connection successful issue but can explain a bit more about the environment hierarchy.

VrepEnv is the base environment, handling the common code for any environment that communicates with VREP.
SawyerEnv extends this and handles common code for VREP envs that use a Sawyer robot.
SawyerReacherEnv extends SawyerEnv and iirc is the simple reacher task for that robot (reach a point in space).
GoalDrivenEnv extends SawyerEnv and has common code for the tasks that extend it like DishRackEnv and ReachOverWallEnv. These tasks are goal-driven as they require the robot to reach a goal position and orientation.

So I think you want to start with something like SawyerReacherEnv and then something like DishRackEnv/ReachOverWallEnv when you introduce your obstacle.

Yes all curricula are pre-defined, automated generation of them was not possible at the time as the environment in VREP could not be manipulated through the API. See the full report and future work sections for more details on this.

Best of luck, feel free to reach out with other questions.

**Comment by rohitdhak** [comment]
Thanks for the information. 
And I really appreciate the clarification. 

And I am sure I will reach out to you again :)
